id: P4C3BA403
initial_creation_type: ocr
source_metadata:
  volumes:
    01f509402c524f929f6a878fa6eb5316:
      base_file: v038.txt
      image_group_id: I1PD95883
      title: དེ་བཞིན་གཤེགས་པ་བདུན་གྱི་སྔོན་གྱི་སྨོན་ལམ་གྱི་ཁྱད་པར་རྒྱས་པའི་མདོ་སྡེའི་མན་ངག།
      total_pages: 1044
      volume_number: 38
